name: Display PR Details

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  display-pr-details:
    runs-on: ubuntu-latest
    steps:
    - name: Extract PR information
      id: extract-info
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        PR_TITLE=${{ github.event.pull_request.title }}
        PR_BODY=${{ github.event.pull_request.body }}
        PR_USER=${{ github.event.pull_request.user.login }}
        
        # 将标签名称提取为以逗号分隔的字符串
        PR_LABELS=$(echo "${{ toJson(github.event.pull_request.labels) }}" | jq -r 'map(.name) | join(", ")')
        
        echo "PR_NUMBER=${PR_NUMBER}" >> $GITHUB_ENV
        echo "PR_TITLE=${PR_TITLE}" >> $GITHUB_ENV
        echo "PR_BODY=${PR_BODY}" >> $GITHUB_ENV
        echo "PR_USER=${PR_USER}" >> $GITHUB_ENV
        echo "PR_LABELS=${PR_LABELS}" >> $GITHUB_ENV

    - name: Display PR details
      run: |
        echo "Pull Request Number: ${{ env.PR_NUMBER }}"
        echo "Pull Request Title: ${{ env.PR_TITLE }}"
        echo "Pull Request Body: ${{ env.PR_BODY }}"
        echo "Pull Request User: ${{ env.PR_USER }}"
        echo "Pull Request Labels: ${{ env.PR_LABELS }}"
