name: Deploy Sphinx docs to GitHub Pages

on:
  push:
    branches:
      - main  # 如主分支为 master 可改为 master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r source/requirements.txt

      - name: Generate documentation from project READMEs
        run: |
          python scripts/generate_docs.py

      - name: Build docs
        run: |
          sphinx-build -b html source source/_build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: source/_build/html 